### ISSUE TITLE
Crud failed 

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#103]
_Original author: madani...@gmail.com (February 24, 2012 20:42:22)_

hi,
I use Doctrine as data source for my grid , when i define a table alias in my doctrine query , i can't do the crud operation ( only delete and update, insert work fine). i have a error message as this 
---------------------- error message --------------
Message: Couldn't find class ct
Stack trace:
#0 C:\Program Files (x86)\Zend\Apache2\htdocs\Principasol\library\Doctrine\Table.php(249): Doctrine_Table-&gt;initDefinition()
#1 C:\Program Files (x86)\Zend\Apache2\htdocs\Principasol\library\Doctrine\Connection.php(1126): Doctrine_Table-&gt;__construct('ct', Object(Doctrine_Connection_Mysql), true)
#2 C:\Program Files (x86)\Zend\Apache2\htdocs\Principasol\library\Doctrine\Query.php(1924): Doctrine_Connection-&gt;getTable('ct')
#3 C:\Program Files (x86)\Zend\Apache2\htdocs\Principasol\library\Doctrine\Query.php(1722): Doctrine_Query-&gt;loadRoot('ct', 'ct')
#4 C:\Program Files (x86)\Zend\Apache2\htdocs\Principasol\library\Doctrine\Query\Where.php(76): Doctrine_Query-&gt;load('ct', false)

---

I use the latest version of zfdatagrid (0.8) , zendF(1.11) 
my select query is like :
$select=Doctrine_Query::create()-&gt;select('ct.ctc_prenom,ct.ctc_nom,ct.ctc_service,ct.ctc_fonction,ct.ctc_numerotelephone,ct.ctc_email,to.ogn_nom ')-&gt;from('TContact ct')-&gt;leftJoin('ct.TOrganisation to ');

to.ogn_nom is foreigen key of (ogn_id =&gt;TOrganisation) in TContact

my Doctrine.php code is the same in svn 

Thanks for the support.

<b>Please insert the appropriate values;</b>
                    Zend Framework version:1.11
ZFDatgrid Version (Bvb_Grid::getVersion(0.8)):0.8
                          Operating system: win 7
                               PHP Version:5.3
               Database Server and version:mysql5
                          Source Adatapter:doctrine

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=828_

**Comment by imonteiro** [comment]
_From madani...@gmail.com on February 26, 2012 08:22:45_
Thanks for the support.

**Comment by imonteiro** [comment]
_From madani...@gmail.com on February 29, 2012 15:19:46_
I use the latest version of zfdatagrid (0.8) , zendF(1.11) 
my select query is like :
$select=Doctrine_Query::create()->select('ct.ctc_prenom,ct.ctc_nom,ct.ctc_service,ct.ctc_fonction,ct.ctc_numerotelephone,ct.ctc_email,to.ogn_nom ')->from('TContact ct')->leftJoin('ct.TOrganisation to ');

to.ogn_nom is foreigen key of (ogn_id =>TOrganisation) in TContact

my Doctrine.php code is the same in svn 

Thanks for the support.
