### ISSUE TITLE
Erro exportando pdf

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#266]
_Original author: alessand...@gmail.com (May 11, 2011 19:51:23)_

Quando clico na imagem pdf do grid recebo o erro :

Message: call to unknown function getForm

Stack trace:
#0 [internal function]: Bvb_Grid-&gt;__call('getForm', Array)
#1 C:\xampp\htdocs\snp\application\modules\admin\controllers\animalController.php(182): Bvb_Grid_Deploy_Pdf-&gt;getForm(1)
#2 C:\xampp\htdocs\snp\library\Zend\Controller\Action.php(513): Admin_AnimalController-&gt;listAction()
#3 C:\xampp\htdocs\snp\library\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action-&gt;dispatch('listAction')
#4 C:\xampp\htdocs\snp\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard-&gt;dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#5 C:\xampp\htdocs\snp\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front-&gt;dispatch()
#6 C:\xampp\htdocs\snp\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap-&gt;run()
#7 C:\xampp\htdocs\snp\public\index.php(86): Zend_Application-&gt;run()
#8 {main}

Request Parameters:

array (
  'module' =&gt; 'admin',
  'controller' =&gt; 'animal',
  'action' =&gt; 'list',
  '_exportTo' =&gt; 'pdf',
) 

Obrigado

<b>What steps will reproduce the problem?</b>
<b>1.</b>
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

<b>Please insert the appropriate values;</b>
<b>Zend Framework version:</b>
<b>ZFDatgrid Version (Bvb_Grid::getVersion()):</b>
<b>Operating system:</b>
<b>PHP Version:</b>
<b>Database Server and version:</b>
<b>Source Adatapter:</b>

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=658_

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 11, 2011 20:46:15_
Acontece isso quando uso : $grid->getForm(1)->removeElement('pes_dt');

Se tirar esta linha exporta normalmente.

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 12, 2011 00:29:50_
Boas,

O Pdf não tem o método form

Faz o seguinte

<code>
if(!$this->getExport())
{
    $grid->getForm(1)->removeElement('pes_dt');
}
</code>

Best Regards,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 12, 2011 14:05:52_
Olá Bento

Recebo o erro :

Application error

Exception information:

Message: Method "getExport" does not exist and was not trapped in __call()

Stack trace:

#0 [internal function]: Zend_Controller_Action->__call('getExport', Array)
#1 C:\xampp\htdocs\snp\application\modules\admin\controllers\animalController.php(182): Admin_AnimalController->getExport()
#2 C:\xampp\htdocs\snp\library\Zend\Controller\Action.php(513): Admin_AnimalController->listAction()
#3 C:\xampp\htdocs\snp\library\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action->dispatch('listAction')
#4 C:\xampp\htdocs\snp\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#5 C:\xampp\htdocs\snp\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#6 C:\xampp\htdocs\snp\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#7 C:\xampp\htdocs\snp\public\index.php(87): Zend_Application->run()
#8 {main}  
Request Parameters:

array (
  'module' => 'admin',
  'controller' => 'animal',
  'action' => 'list',
)

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 12, 2011 14:10:12_
Resovido troquei o $this por $grid ! 

Obrigado

Alessandro

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 12, 2011 17:57:07_
Olá Bento estou usando : 

if(!$grid->getExport()){
                $date = $grid->getForm(1)->getElement('ani_dt_nasc')->getValue();
        $date = date('d/m/Y',strtotime($date));
        $grid->getForm(1)->getElement('ani_dt_nasc')->setValue($date);

}

Mas a formatação da data no campo não funciona.

Obrigado

Alessandro

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 12, 2011 20:43:49_
Boas,

Não é getExport() mas sim isExport()

Deculpa lá o erro

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 12, 2011 21:15:21_
Ok agora assim, obrigado Bento!
