### ISSUE TITLE
Como converter datas do form para o mysql

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#267]
_Original author: alessand...@gmail.com (May 11, 2011 17:45:17)_

No BVB_GRID_FORM tem um campo que o usuario insere a data no formato
dd/mm/yyyy e o mysql é YYYY-MM-dd como fazer para converter?

Obrigado

<b>What is the expected output? What do you see instead?</b>

<b>Please insert the appropriate values;</b>
<b>Zend Framework version:</b>
<b>ZFDatgrid Version (Bvb_Grid::getVersion()):</b>
<b>Operating system:</b>
<b>PHP Version:</b>
<b>Database Server and version:</b>
<b>Source Adatapter:</b>

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=657_

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 12, 2011 00:37:47_
Boas,

Tens duas formas de o fazer.

Ou adicionas um evento antes da introdução de dados na bd, ou utilizas filters

Para utilizares filters

<code>
$grid->getForm(1)->getElement('data')->addFilter('oMeuFiltro');
</code>

Mais informações sobre filtros aqui: http://framework.zend.com/manual/en/zend.form.elements.html#zend.form.elements.filters

Para utilizares eventos

<code>
function aMinhaFuncao ($event)
{
    $event->setParam('data',strtotime($event->getParam('data'),'Y-m-d'));#Muda data para o nome do campo 
}
$grid->listenEvent('crud.before_insert','aMinhaFuncao');
$grid->listenEvent('crud.before_update','aMinhaFuncao');
</code>

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 12, 2011 01:04:29_
Olá Bento, como fazer para esta função ser callable?

$grid->listenEvent('crud.before_update','aMinhaFuncao');

  function aMinhaFuncao ($event) {  
    $event->setParam('ani_dt_nasc',date('Y-m-d H:i:s',strtotime($event->getParam('ani_dt_nasc'))));
  }

eu recebo o erro : 

Message: aMinhaFuncao not callable

Stack trace:
#0 C:\xampp\htdocs\snp\library\Bvb\Grid.php(4332): Bvb_Grid_Event_Dispatcher->connect('crud.before_upd...', 'aMinhaFuncao')
#1 C:\xampp\htdocs\snp\application\modules\admin\controllers\animalController.php(252): Bvb_Grid->listenEvent('crud.before_upd...', 'aMinhaFuncao')
#2 C:\xampp\htdocs\snp\library\Zend\Controller\Action.php(513): Admin_AnimalController->listAction()
#3 C:\xampp\htdocs\snp\library\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action->dispatch('listAction')
#4 C:\xampp\htdocs\snp\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#5 C:\xampp\htdocs\snp\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#6 C:\xampp\htdocs\snp\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#7 C:\xampp\htdocs\snp\public\index.php(87): Zend_Application->run()
#8 {main}  
Request Parameters:
array (
  'module' => 'admin',
  'controller' => 'animal',
  'action' => 'list',
)

Obrigado

Alessandro Ferreira

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 12, 2011 01:13:26_
Boas,

Experimenta assim:

$grid->listenEvent('crud.before_update',array($this,'aMinhaFuncao'));

function aMinhaFuncao ($event) {  
    $event->setParam('ani_dt_nasc',date('Y-m-d H:i:s' , strtotime( $event->getParam('ani_dt_nasc'))));
}

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 12, 2011 01:25:48_
Bento

Parou de dar o erro mas não insere nada na tabela.

Obrigado

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 12, 2011 01:37:41_
Bento
Não poderia ser por uma funcao de callback do form tipo

$form->setCallbackBeforeUpdate $callback ?

Se sim como poderia implementar isso?

Obrigado

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 12, 2011 01:44:32_
Boas,

O callback foi removido em favor de eventos.

Quando dizes que não inserir nada na tabela, não insere nenhum registo ou o campo ani_dt_nas está em branco?

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 12, 2011 01:45:53_
Olá Bento

Ele fica '0000-00-00'

Obrigado

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 12, 2011 01:54:43_
boas,

Desculpa lá, faz o seguinte.

 function aMinhaFuncao ($event)
     {
       $values = $event->getParam('values');
       $values['ani_dt_nasc'] = strtotime($values['ani_dt_nasc'],'Y-m-d H:i:s');
       $event->setParam('values',$values);
     }

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 12, 2011 02:04:26_
Olá Bento, 

Ficou do mesmo jeito : '0000-00-00'

Obrigado

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 12, 2011 02:19:34_
Boas,

Faz o seguinte:

 function aMinhaFuncao ($event)
     {
       $values = $event->getParam('values');
       echo "<pre>";
       print_r($values);
       die();

```
   $values['ani_dt_nasc'] = strtotime($values['ani_dt_nasc'],'Y-m-d H:i:s');
   $event->setParam('values',$values);
 }
```

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 12, 2011 10:35:25_
Olá Bento

continua da mesma forma e não printou(print_r) nada também.

Obrigado.

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 12, 2011 21:09:38_
Alessandro,

Não tenho estado mesmo nos meus dias.

Pensei que estivesses a utilizar o método before_inser e não before_update.

Nessa caso não é values, mas sim newValues

 function aMinhaFuncao ($event)
     {
       $values = $event->getParam('newValues');
       $values['ani_dt_nasc'] = strtotime($values['ani_dt_nasc'],'Y-m-d H:i:s');
       $event->setParam('newValues',$values);
     }

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From thiagote...@gmail.com on May 16, 2011 18:30:45_
OK, deu certo usei o svn do proprio zend studio, só uma dívida a função ali precisa estar dentro da Action mesmo, ou posso criar uma public function update para chamar.

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 16, 2011 18:36:14_
Boas,

Podes colocar a função onde quiseres.

Tens é que depois especificar o scope.

Imagina que tens um ficheiro com funções.

Fazes assim:

$grid->listenEvent('crud.before_update','aMinhaFuncao');

Mas se for um método tens que especificar em que classe está. No caso de estar dentro da classe actual usas

$grid->listenEvent('crud.before_update',array($this,'aMinhaFuncao'));

Se estiver dentro de outra classe usas

$grid->listenEvent('crud.before_update',array('ONomeDaMinhaClasse','aMinhaFuncao'));

Com os melhores cumprimentos,
Bento Vilas Boas
