### ISSUE TITLE
Estou recebendo o erro ao editar : Too few columns for the primary key

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#271]
_Original author: alessand...@gmail.com (May 10, 2011 20:50:29)_

Message: Too few columns for the primary key.

Stack trace:
#0 [internal function]: Zend_Db_Table_Abstract-&gt;find()
#1 C:\xampp\htdocs\snp\library\Bvb\Grid\Source\Zend\Table.php(204): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\snp\library\Bvb\Grid\Deploy\Table.php(294): Bvb_Grid_Source_Zend_Table-&gt;getRecord('animais', Array)
#3 C:\xampp\htdocs\snp\library\Bvb\Grid\Deploy\Table.php(3001): Bvb_Grid_Deploy_Table-&gt;_buildFormValues()
#4 C:\xampp\htdocs\snp\application\modules\admin\controllers\animalController.php(171): Bvb_Grid_Deploy_Table-&gt;setForm(Object(Bvb_Grid_Form))
#5 C:\xampp\htdocs\snp\library\Zend\Controller\Action.php(513): Admin_AnimalController-&gt;listAction()
#6 C:\xampp\htdocs\snp\library\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action-&gt;dispatch('listAction')
#7 C:\xampp\htdocs\snp\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard-&gt;dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#8 C:\xampp\htdocs\snp\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front-&gt;dispatch()
#9 C:\xampp\htdocs\snp\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap-&gt;run()
#10 C:\xampp\htdocs\snp\public\index.php(59): Zend_Application-&gt;run()
#11 {main}

Request Parameters:

array (
  'module' =&gt; 'admin',
  'controller' =&gt; 'animal',
  'action' =&gt; 'list',
  'zfmassedit' =&gt; '1',
  'edit' =&gt; '1',
)  

<b>What is the expected output? What do you see instead?</b>

<b>Please insert the appropriate values;</b>
<b>Zend Framework version:</b>
<b>ZFDatgrid Version (Bvb_Grid::getVersion()):</b>
<b>Operating system:</b>
<b>PHP Version:</b>
<b>Database Server and version:</b>
<b>Source Adatapter:</b>

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=653_

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 10, 2011 20:52:40_
Boas,

Podes enviar-me o DDL da tabela e a URL de edição?

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 10, 2011 21:10:18_

## Estrutura da tabela `animais`

CREATE TABLE IF NOT EXISTS `animais` (
  `ani_id` int(11) NOT NULL AUTO_INCREMENT,
  `ani_nome` varchar(255) DEFAULT NULL,
  `ani_classificacao` varchar(45) DEFAULT NULL,
  `ani_idade` float DEFAULT NULL,
  `ani_dt_nasc` date NOT NULL,
  `ani_dt_morte` date DEFAULT NULL,
  `ani_desc` varchar(45) DEFAULT NULL,
  `ani_composicao` varchar(45) DEFAULT NULL,
  `ani_sexo` enum('Macho','Femea','ND') NOT NULL DEFAULT 'ND',
  `ani_gr_sangue` varchar(45) DEFAULT NULL,
  `ani_criador_fk` varchar(45) DEFAULT NULL,
  `ani_faz_fk` varchar(45) DEFAULT NULL,
  `ani_tec_insp_fk` varchar(45) DEFAULT NULL,
  `ani_crvm_ti_crea` varchar(45) DEFAULT NULL,
  `ani_dt_emissao` date DEFAULT NULL,
  `ani_resp_tec_fk` varchar(45) DEFAULT NULL,
  `ani_crv_crea_rt_fk` varchar(45) DEFAULT NULL,
  `ani_pai_fk` int(11) DEFAULT NULL,
  `ani_mae_fk` int(11) DEFAULT NULL,
  `ani_peso_nasc` float DEFAULT NULL,
  `ani_peso_desmama` float DEFAULT NULL,
  `ani_peso_14m` float DEFAULT NULL,
  `ani_pe_14_cm` float DEFAULT NULL,
  `ani_ganho_peso_desm_14m` float DEFAULT NULL,
  `ani_per_escr_14m` varchar(45) DEFAULT NULL,
  `ani_musc_14m` varchar(45) DEFAULT NULL,
  `ani_reg_imp` varchar(45) DEFAULT NULL COMMENT 'Registro de Importação\n',
  PRIMARY KEY (`ani_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=10 ;

URL 
http://localhost/snp/public/admin/animal/list/zfmassedit/1/edit/1

Model

<?php
/**
- AnimaisModel
- 
- @author Alessandro Ferreira
- @version 
  */
  require_once 'Zend/Db/Table/Abstract.php';

class Application_Model_Animais extends Zend_Db_Table_Abstract
{
    //Nome tabela
    protected $_name = 'animais';

```
//Nome chave primária
protected $_primary = array('ani_id');
```

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 10, 2011 21:21:33_
Boas,

Podes enviar-me o código PHP da grid para o email geral[symbol]petala-azul.com

É que experimentei com a tua tabela e funciona normalmente

Vê anexo

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 10, 2011 21:33:35_
Mandei no seu email geral[symbol]petala-azul.com . Obrigado

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 10, 2011 21:40:11_
Testei com outra tabela e o erro persiste. Mais uma informação estou trabalhando com Modules. 

Request Parameters:

array (
  'module' => 'admin',
  'controller' => 'animal',
  'action' => 'list',
  'zfmassedit' => '1',
  'edit' => '1',
)  

Obrigado

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 10, 2011 21:44:42_
Boas,

Não podes actualizar a tua versão através de SVN?

Tens instalada a revision 1607 e a última é a 1718

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 10, 2011 21:47:17_
Ok vou atualizar

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 10, 2011 22:06:03_
Ok atualizei a versão e funcionou direitinho!

Mais uma vez muito obrigado!

Alessandro

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 10, 2011 22:06:41_
Ok atualizei a versão e funcionou direitinho!

Mais uma vez muito obrigado!

Alessandro
