### ISSUE TITLE
AddElement() campos ficam fora do form

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#275]
_Original author: alessand...@gmail.com (May 04, 2011 19:41:25)_

Quando uso o addElement no form os campos adicionados ficam fora do form.

<b>What is the expected output? What do you see instead?</b>

<b>Please insert the appropriate values;</b>
                    Zend Framework version:1.10
ZFDatgrid Version (Bvb_Grid::getVersion()):0.7.1
                          Operating system:windows
                               PHP Version:5
               Database Server and version:mysql
                          Source Adatapter:db_table

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=649_

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 04, 2011 22:54:49_
Boas,

É um problema dos decorators.

$grid->getForm(1)->addElement(...)->setDecorators($grid->getForm(1)->getSubFormDecorator());

Deve resolver o teu problema.

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 05, 2011 02:35:13_
Olá Bento,

Fiz assim:

```
    $form = new Bvb_Grid_Form();     
    $form->setBulkAdd(1)->setAdd(true)->setEdit(true)->setBulkDelete(true)->setBulkEdit(true)->setDelete(true)->setAddButton(true)->setSaveAndAddButton(true);

    $grid->setForm($form); 
    $grid->getForm(1)->addElement('select','ani_mae_fk',array('label'=>'Mãe','multiOptions'=>$optF));
    $grid->getForm(1)->setDecorators($grid->getForm(1)->getSubFormDecorator());
```

E está dando um erro : 

An error occurred
Application error
Exception information:

Message: Method getSubFormDecorator does not exist

Stack trace:
#0 [internal function]: Zend_Form->__call('getSubFormDecor...', Array)
#1 C:\xampp\htdocs\snp\application\modules\admin\controllers\animalController.php(176): Zend_Form_SubForm->getSubFormDecorator()
#2 C:\xampp\htdocs\snp\library\Zend\Controller\Action.php(513): Admin_AnimalController->listAction()
#3 C:\xampp\htdocs\snp\library\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action->dispatch('listAction')
#4 C:\xampp\htdocs\snp\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#5 C:\xampp\htdocs\snp\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#6 C:\xampp\htdocs\snp\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#7 C:\xampp\htdocs\snp\public\index.php(63): Zend_Application->run()
#8 {main}  
Request Parameters:

array (
  'module' => 'admin',
  'controller' => 'animal',
  'action' => 'list',
)  

Obrigado,

Alessandro Ferreira

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 05, 2011 02:48:46_
Boas,

Experimenta assim

<code>

```
    $form = new Bvb_Grid_Form();     
    $form->setBulkAdd(1)->setAdd(true)->setEdit(true)->setBulkDelete(true)->setBulkEdit(true)->setDelete(true)->setAddButton(true)->setSaveAndAddButton(true);
```

$grid->setForm($form); 
        $grid->getForm(1)->addElement('select','ani_mae_fk',array('label'=>'Mãe','multiOptions'=>$optF));
$grid->getForm(1)->getElement('ani_mae_fk')->setDecorators($grid->getForm()->getSubFormDecorator());

</code>

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 05, 2011 14:38:27_
Olá Bento,
O erro continua.

An error occurred
Application error
Exception information:
Message: Method getSubFormDecorator does not exist

Alessandro Ferreira

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 05, 2011 21:59:29_
Boas,

Desculpa lá, não estava a prestar atenção ao que fazia.

Coloca este código:

<code>
$grid->getForm(1)->addElement('select','ani_mae_fk',array('label'=>'Mãe','multiOptions'=>>$optF));
$grid->getForm(1)->getElement('ani_mae_fk')->setDecorators($form->getSubformElementDecorator());
</code>

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From alessand...@gmail.com on May 06, 2011 01:03:58_
Olá Bento,

Problema resolvido! Thank´s

Alessandro Ferreira
