### ISSUE TITLE
Doctrine usage in 0.7.1 Broken?

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#313]
_Original author: f.napole...@gmail.com (March 03, 2011 01:29:38)_

This is my first attempt to use your project in an existing ZF project with Doctrine. I try with a minimal setup.

<b>What steps will reproduce the problem?</b>
1. Downloaded 0.7.1 version in library
2. added this line to application.ini
autoloadernamespaces[] = &quot;Bvb_&quot;
3. added this code to the controller
        $grid = Bvb_Grid::factory('Table');
        $grid-&gt;setSource(new Bvb_Grid_Source_Doctrine('Group')); // Group is a Doctrine model
        $this-&gt;view-&gt;grid = $grid-&gt;deploy();

<b>What is the expected output? What do you see instead?</b>

I'd expect a simple grid at least at html level, instead I obtain this exception

Couldn't find class Array
#0 /Users/fabionapoleoni/Desktop/work/phpStorm/mystery/library/Doctrine/Table.php(256): Doctrine_Table-&gt;initDefinition()
#1 /Users/fabionapoleoni/Desktop/work/phpStorm/mystery/library/Doctrine/Connection.php(1126): Doctrine_Table-&gt;__construct(Array, Object(Doctrine_Connection_Mysql), true)
#2 /Users/fabionapoleoni/Desktop/work/phpStorm/mystery/library/Doctrine/Core.php(1085): Doctrine_Connection-&gt;getTable(Array)
#3 /Users/fabionapoleoni/Downloads/Bvb/Grid/Source/Doctrine.php(994): Doctrine_Core::getTable(Array)
#4 /Users/fabionapoleoni/Downloads/Bvb/Grid/Source/Doctrine.php(898): Bvb_Grid_Source_Doctrine-&gt;_findAndSetSelect()
#5 /Users/fabionapoleoni/Downloads/Bvb/Grid/Source/Doctrine.php(58): Bvb_Grid_Source_Doctrine-&gt;_setSelectParts()
#6 /Users/fabionapoleoni/Desktop/work/phpStorm/mystery/application/controllers/IndexController.php(17): Bvb_Grid_Source_Doctrine-&gt;__construct('Group')
#7 /Users/fabionapoleoni/Downloads/ZendFramework-1.10.8/library/Zend/Controller/Action.php(513): IndexController-&gt;indexAction()
#8 /Users/fabionapoleoni/Downloads/ZendFramework-1.10.8/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action-&gt;dispatch('indexAction')
#9 /Users/fabionapoleoni/Downloads/ZendFramework-1.10.8/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard-&gt;dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /Users/fabionapoleoni/Downloads/ZendFramework-1.10.8/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front-&gt;dispatch()
#11 /Users/fabionapoleoni/Downloads/ZendFramework-1.10.8/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap-&gt;run()
#12 /Users/fabionapoleoni/Desktop/work/phpStorm/mystery/public/index.php(17): Zend_Application-&gt;run()
#13 {main}

I debugged the code and the problem seems to be in the fact that the _setFromParts method is called twice by the constructor.

If I apply the attached patch to the 0.7.1 version it works and displays a basic grid with no images and no javascript. I don't know if my patch breaks some other functionality.

<b>Please insert the appropriate values;</b>
<b>Zend Framework version:</b>
1.10.8
<b>ZFDatgrid Version (Bvb_Grid::getVersion()):</b>
0.7.1
<b>Operating system:</b>
MacOS X 10.6.6
<b>PHP Version:</b>
PHP 5.3.5 (cli) (built: Jan 27 2011 03:57:25) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
    with Xdebug v2.1.0, Copyright (c) 2002-2010, by Derick Rethans

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=608_

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on March 03, 2011 01:51:44_
Hi,

Patch applied. Thanks for that.

For JS please paste this code in your template.

<?php echo $this->headScript();?>

for images, you must define their location using

$grid->setImagesUrl('url/to/images');

Best Regards,
Bento Vilas Boas
