### ISSUE TITLE
filter render date problem with export

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#422]
_Original author: tho...@valepizza.com (November 01, 2010 10:58:53)_

Na última revisão quando utilizo um filtro 'render'=&gt;'date', e mando gerar uma exportação &quot;PDF&quot; por exemplo, não me traz nada no export, somente na grid.

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=486_

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on November 01, 2010 11:06:28_
Outro erro que ocorre, é quando faço um filtro por data: de/até

Message: Plugin by name 'Date' was not found in the registry; used paths: Bvb_Grid_Filters_Render_Pdf_: Bvb/Grid/Filters/Render/Pdf/
Stack trace:

#0 /var/www/lib/Bvb/Grid.php(3468): Zend_Loader_PluginLoader->load('Date')
#1 /var/www/lib/Bvb/Grid.php(1204): Bvb_Grid->loadFilterRender('date')
#2 /var/www/lib/Bvb/Grid.php(2447): Bvb_Grid->_buildFiltersValues()
#3 /var/www/lib/Bvb/Grid/Deploy/Pdf.php(119): Bvb_Grid->deploy()

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on November 01, 2010 11:11:08_
O primeiro problema mensionado ocorre somente se informo a data "de", e deixo "até" em branco

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on November 19, 2010 18:37:43_
Alguma novidade quanto a este problema?
não consigo exportar a tabela quando utilizo filtro por data...
abraços!

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on December 09, 2010 23:23:52_
Boas,

Acabei de lançar agora o projecto que me manteve ocupado, vou ter agora mais tempo para a grid.

Faz a actualização para a última revision. Já tem lá um fix.

desculpa lá pelo tempo de espera.

Com os melhores cumprimentos,
Bento Vilas Boas
