### ISSUE TITLE
Bvb_Grid_Source_Zend_Table fails if db_table schema is different than adapter's dbname

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#469]
_Original author: jg%proz....@gtempaccount.com (September 10, 2010 02:05:55)_

<b>What steps will reproduce the problem?</b>
1. Configure PDO_Mysql adapter using a particular dbname
2. Create a Zend_Db_Table subclass with $_schema set to a different database than the adapter dbname
3. Instantiate a grid and setSource() to an instance of that Zend_Db_Table subclass

<b>What is the expected output? What do you see instead?</b>

I expect to see the grid output. Instead, I see an application error:

Message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'proz.entity_relationships' doesn't exist

In this case, &quot;proz&quot; is the dbname in the adapter, but the $_schema defined in the table class should be &quot;social&quot;. The defined $_schema is not used in the call to Bvb_Grid_Source_Zend_Select-&gt;getDescribeTable().

<b>Please insert the appropriate values;</b>
                    Zend Framework version: 1.10.7
ZFDatgrid Version (Bvb_Grid::getVersion()): 0.6.5
                          Operating system: Debian Linux
                               PHP Version: 5.2.8
               Database Server and version: Mysql 5.0.20
                          Source Adatapter: Pdo_Mysql

<b>Please provide any additional information below.</b>

My adapter config:

resources.db.adapter = &quot;Pdo_Mysql&quot;
resources.db.params.dbname = &quot;proz&quot;

My dbtable class:

class Application_Model_DbTable_Relationships extends Zend_Db_Table_Abstract {
  protected $_schema = 'social'; // db name
  protected $_name = 'entity_relationships'; // Table name
  protected $_primary = 'entity_relationship_id'; // Primary key
}

Application error and stack trace:

Exception information:

Message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'proz.entity_relationships' doesn't exist

Stack trace:
#0 /home/pages/proz/contrib/Zend-Framework-1.10.7/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /home/pages/proz/contrib/Zend-Framework-1.10.7/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /home/pages/proz/contrib/Zend-Framework-1.10.7/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query('DESCRIBE `entit...', Array)
#3 /home/pages/proz/contrib/Zend-Framework-1.10.7/library/Zend/Db/Adapter/Pdo/Mysql.php(156): Zend_Db_Adapter_Pdo_Abstract-&gt;query('DESCRIBE `entit...')
#4 /home/pages/dev-jg/proz-zf/library/Bvb/Grid/Source/Zend/Select.php(198): Zend_Db_Adapter_Pdo_Mysql-&gt;describeTable('entity_relation...')
#5 /home/pages/dev-jg/proz-zf/library/Bvb/Grid/Source/Zend/Select.php(147): Bvb_Grid_Source_Zend_Select-&gt;getDescribeTable('entity_relation...')
#6 /home/pages/dev-jg/proz-zf/library/Bvb/Grid.php(445): Bvb_Grid_Source_Zend_Select-&gt;buildFields()
#7 /home/pages/dev-jg/proz-zf/application/controllers/RelationshipsController.php(29): Bvb_Grid-&gt;setSource(Object(Bvb_Grid_Source_Zend_Table))
#8 /home/pages/proz/contrib/Zend-Framework-1.10.7/library/Zend/Controller/Action.php(513): RelationshipsController-&gt;indexAction()
#9 /home/pages/proz/contrib/Zend-Framework-1.10.7/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action-&gt;dispatch('indexAction')
#10 /home/pages/proz/contrib/Zend-Framework-1.10.7/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard-&gt;dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /home/pages/proz/contrib/Zend-Framework-1.10.7/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front-&gt;dispatch()
#12 /home/pages/proz/contrib/Zend-Framework-1.10.7/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap-&gt;run()
#13 /home/pages/dev-jg/proz/index-zf.php(34): Zend_Application-&gt;run()
#14 /home/pages/dev-jg/proz/index-precontroller.php(24): require('/home/pages/dev...')
#15 /home/pages/dev-jg/proz/index.php(2): require_once('/home/pages/dev...')
#16 {main}

Thanks,

Jason

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=436_

**Comment by imonteiro** [comment]
_From jg%proz....@gtempaccount.com on September 10, 2010 04:12:27_
I made some changes to the code that seem to fix the problem for me. I've attached a patch. I hope it's useful. Thanks for your efforts on such a great project.

Jason

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on September 11, 2010 15:13:11_
HI,

Thanks for the patch

Already applied and committed

Best Regards,
Bento Vilas Boas
