### ISSUE TITLE
Mistake in Bvb_Grid_Deploy_Table

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#487]
_Original author: braun.a...@gmail.com (August 16, 2010 12:09:15)_

Hi,

You forget to refactor this

Bvb_Grid_Deploy_Table line #1399 (rev 1374):

...instanceof Bvb_Grid_Template_Table_Table...

Bye
Akos

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=418_

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on August 16, 2010 12:15:06_
Message: Plugin by name 'Table' was not found in the registry; used paths: My_Template_Table_: My/Template/Table/ Bvb_Grid_Template_: Bvb/Grid/Template/Table/

**Comment by imonteiro** [comment]
_From tsen...@gmail.com on August 17, 2010 17:09:04_
#0 /var/www/lib/Bvb/Grid.php(2181): Zend_Loader_PluginLoader->load('table', 'table')
#1 /var/www/lib/Bvb/Grid/Deploy/Table.php(1400): Bvb_Grid->setTemplate('table', 'table', Array)
#2 /var/www/sistemas/aprovesc/financeiro/modules/xxxx(537): Bvb_Grid_Deploy_Table->deploy()

**Comment by imonteiro** [comment]
_From braun.a...@gmail.com on August 17, 2010 22:50:46_
Bento should only change
Bvb_Grid_Template_Table_Table -> Bvb_Grid_Template_Table

but he knows it, so we wait...

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on August 17, 2010 23:14:10_
Hi guys,

Sorry about this.

I wasn't working with latest SVN revision, so I was completely missing the point here :)

Everything should be working right now.

Best Regards,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From ruben.f...@gmail.com on March 23, 2011 16:52:01_
I'm still getting that error...

Plugin by name 'Table' was not found in the registry; used paths:
Bvb_Grid_Template_: Bvb/Grid/Template/

What do I need to do in order to fix that bug?

Thanks in advance
Kind regards

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on March 23, 2011 19:02:15_
Hi Ruben

What version are you using?

Best Regards,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From ruben.f...@gmail.com on March 23, 2011 19:28:44_
Hola Bento
I copy the library from ZFDatagrid 0.7.1.zip.
To be honest, I found many versions of the grid so I sticked with the one from that zip file. Let me know if there is a newer version.
Thanks in advance!

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on March 24, 2011 00:27:37_
Hi Ruben,

Is this the message you get?

[CODE]
Message: Plugin by name 'Table' was not found in the registry; used paths: My_Template_Table_: My/Template/Table/ Bvb_Grid_Template_: Bvb/Grid/Template/Table/ 
[/CODE]

Best Regards,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From ruben.f...@gmail.com on March 24, 2011 07:48:25_
Hi Bento, no, I get this one:

[code]
Plugin by name 'Table' was not found in the registry; used paths:
Bvb_Grid_Template_: Bvb/Grid/Template/
[/code]

**Comment by imonteiro** [comment]
_From ruben.f...@gmail.com on March 24, 2011 08:20:57_
By the way, I printed the version. I get this one: $Rev: 1607 $

**Comment by imonteiro** [comment]
_From ruben.f...@gmail.com on March 24, 2011 10:32:56_
It's working OK now. I'm using the version of the SVN.

**Comment by imonteiro** [comment]
_From mtaylorl...@gmail.com on July 23, 2012 14:30:31_
I have this problem too 

using the latest version of zfdatagrid

Zend framework 1.10.6 

$grid = Bvb_Grid::factory("Bvb_Grid_Deploy_Table");
$grid->setSource(new Bvb_Grid_Source_Array($this->pkg));
$myGrid = $grid->deploy();

Here's the error
Plugin by name 'Table' was not found in the registry; used paths: Bvb_Grid_Template_: Bvb/Grid/Template/
