### ISSUE TITLE
Mass actions on view problem

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#508]
_Original author: tho...@valepizza.com (July 19, 2010 14:32:35)_

When i try 
   $grid-&gt;query(new Model_View());
   $grid-&gt;setMassActions(...) 

on a view:
   class Model_View ...
        protected $_name = 'view';
    protected $_primary = 'id_view';

the error message:
Message: No primary key defined in table. Mass actions not available 

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=396_

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on July 19, 2010 21:06:11_
Hi,

ZFDatagrid will check that against your actual db schema.

Is id_view a primary key?

Best Regards,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on July 20, 2010 12:09:07_
i can't create a primary key in a view...
that is the problem, the ZFDatagrid showld keep the protected $_primary in model.

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on July 20, 2010 12:12:58_
can i send more then one parameter in mass action?

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on July 20, 2010 12:16:43_
maybe a "returnParams" like:

$grid->setMassActions(array(array('url' => $grid->getUrl(), returnParams => array('field1','field2','field3'))));

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on July 20, 2010 13:25:17_
Hi Thomas,

The first report should be fixed with latest commit. Please update your code.

About the second:

Can you explain with you example which values should be returned?

Are you expecting field values or just the values passed with returnParams?

Best Regards,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on July 20, 2010 13:36:46_
return the field values! becose in view, i don't have a primary key, and i need more then one field to reference the selected row.

example: date/id_user group view with a sql count function of points 

```
date        id_user   count(points)
```

[x] 2010-07-01  1         10
[x] 2010-07-02  1         4
[ ] 2010-07-01  2         3
[ ] 2010-07-03  1         6
[x] 2010-07-02  2         1

returns: array(array("date"=>"2010-07-01","id_user"=>"1"),array("date"=>"2010-07-02","id_user"=>"1"),array("date"=>"2010-07-02","id_user"=>"2"))

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on August 09, 2010 14:45:44_
Hello!

Can i send another parameter (not primary key) from massActions?
Something created for this?

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on August 09, 2010 14:56:07_
Zend framewrk allow to put this in Zend_Db_Table: 
protected $_primary = array('id_associado', 'vencimento', 'id_grupo');

But the massActions don't work...

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on August 09, 2010 14:57:36_
Return this:

Array
(
    [module] => contas-a-receber
    [controller] => agrupado
    [action] => index
    [postMassIds] => {{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}}
)

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on August 11, 2010 15:15:33_
Hi,

Can you please check the latest revision?

Also you can now define fields to be submitted.

pass an array as second argument with fields to be return within $grid->setMassActions(array('...'),array('field1','field2'));
OR
$grid->addMassActions(array('...'),array('field1','field2'));

Best Regards,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on August 11, 2010 17:23:25_
Show this error:

Message: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id_associado' in field list is ambiguous
Stack trace:

#0 /var/www/lib/Zend/Db/Statement.php(320): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/lib/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 /var/www/lib/Zend/Db/Select.php(686): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#4 /var/www/lib/Bvb/Grid/Source/Zend/Select.php(397): Zend_Db_Select->query(2)
#5 /var/www/lib/Bvb/Grid/Deploy/Table.php(3159): Bvb_Grid_Source_Zend_Select->getMassActionsIds('conta_receber_a...', Array)
#6 /var/www/lib/Bvb/Grid/Deploy/Table.php(1840): Bvb_Grid_Deploy_Table->_buildMassActions()
#7 /var/www/lib/Bvb/Grid/Deploy/Table.php(1778): Bvb_Grid_Deploy_Table->_buildGridRender()
#8 /var/www/sistemas/aprovesc/financeiro/modules/contas-a-receber/controllers/AgrupadoController.php(535): Bvb_Grid_Deploy_Table->deploy()

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on August 11, 2010 17:28:47_
Hi,

Please prefix the field name with table name.

table.field

Best Regards,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on August 11, 2010 17:52:21_
return this:

Array ( [module] => contas-a-receber [controller] => agrupado [action] => index [postMassIds] => {{id_associado-vencimento-id_grupo}} )

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on August 12, 2010 02:14:15_
Hi,

Where did those {{ came from?

Can you please post or email me your controller code?

Best Regards,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on August 23, 2010 12:30:15_
now i have a error like this: 
"No primary key defined in table. Mass actions not available"

but the table have the primary keys

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on August 24, 2010 14:18:45_
The mass action do not be referenced by primary keys..
should be referenced by a specific informed fields
then i can use a view, or wants reference more then one field

Sometimes get confused with table's or model's primary key ..

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on August 28, 2010 15:16:48_
Hi,

This is how I get the "primary key".

If there is a auto_increment field, then I use that as a identifier. If not there will be a search for primary keys.

This is how CRUD operations work.

Related to mass actions,  the verification above will only be made if the user does not specify any columns to be used instead of primary keys.

<code>
$grid->addMassActions(array(array('url' => $grid->getUrl(), 'caption' => 'Remove (Nothing will happen)', 'confirm' => 'Are you sure?')),array('field1','field2'));
</code>

Please make sure you are using latest SVN revision.

Best Regards,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on September 13, 2010 13:36:57_
Last revision:

$grid->setMassActions(array(array('url' => $grid->getUrl(), 'caption' => 'Imprimir', 'confirm' => 'Deseja realmente imprimir os boletos selecionados?')),array('conta_receber_agrupado.id_associado_ref','conta_receber_agrupado.vencimento','conta_receber_agrupado.id_grupo'));

Return this, on manual select:

Array
(
    [module] => contas-a-receber
    [controller] => agrupado
    [action] => index
    [postMassIds] => {{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}},{{id_associado-vencimento-id_grupo}}
)

On "select all", return this: [CODE-DATE-CODE] confuse!

Array
(
    [module] => contas-a-receber
    [controller] => agrupado
    [action] => index
    [postMassIds] => 414-2010-08-25-2,508-2010-08-25-1,226-2010-08-26-5,501-2010-08-27-1,499-2010-08-27-3,139-2010-08-27-1,500-2010-08-27-1,230-2010-08-28-1,471-2010-08-28-3,359-2010-08-28-1,503-2010-08-30-1,226-2010-08-30-5,229-2010-08-30-3,495-2010-08-30-5,40-2010-08-30-1,464-2010-08-30-1,497-2010-08-30-5,434-2010-08-30-3,490-2010-08-30-1,502-2010-08-30-5,408-2010-08-30-4,287-2010-08-30-1,472-2010-08-30-1,402-2010-08-30-3,158-2010-08-30-1,277-2010-08-30-1,228-2010-08-30-5,494-2010-08-30-3,496-2010-08-30-4,461-2010-09-02-2,264-2010-09-02-4,493-2010-09-02-2,158-2010-09-02-1,263-2010-09-03-1,504-2010-09-03-1,505-2010-09-03-1,498-2010-09-04-2,261-2010-09-04-4,427-2010-09-04-2
)

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on September 15, 2010 02:28:19_
Boas,

Podes tentar agora?

Acho que já deve estar resolvido. A primeira situação também...

Também foi adicionado um novo método para definirmos o separador dos valores no post.

$grid->setMassActionsSeparator('-');

$grid->getMassActionsSeparator();

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on September 20, 2010 13:44:03_
Atualizei hj a última revisão
Pelo que eu notei, não houve nenhuma mudança
setMassActionsSeparator também não está funcionando.

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on September 20, 2010 15:08:30_
Boas,

Podes então dizer qual é a revision que estás a utilizar?

Com os melhores cumprimentos,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on September 20, 2010 16:39:56_
1455

**Comment by imonteiro** [comment]
_From tsen...@gmail.com on December 10, 2010 15:46:51_
alguma posição quanto a este problema?

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on December 15, 2010 23:07:20_
tsens81,

Qual é o erro que te dá?

O problema é que eu ainda não consegui reproduzir o erro. Comigo está tudo a funcionar...

Com os melhores cumprimentos,
Bento Vilas Boas
