### ISSUE TITLE
Fulltext search doesn't work

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#529]
_Original author: Vlad.Ovc...@gmail.com (July 09, 2010 09:08:17)_

<b>What steps will reproduce the problem?</b>
1. Create grid for table `users` with the `company` field
2. Update column: $grid-&gt;updateColumn('company', array(
            'title' =&gt; 'Company',
            'search' =&gt; array('fulltext' =&gt; true),
        ));
3. Load page with grid and make search.

```
                Zend Framework version: 1.10.5
```

ZFDatgrid Version (Bvb_Grid::getVersion()): 1310
                          Operating system: Windows Vista
                               PHP Version: 5.2
               Database Server and version: MySQL 5.1
                          Source Adatapter: PDO_MYSQL

Any search throws exception like:

Unrecognized value in extra key
Exception information:

Message: Unrecognized value in extra key
Stack trace:
#0 ...\library\Bvb\Grid.php(1049): Bvb_Grid_Source_Zend_Select-&gt;addFullTextSearch('adfa', 'company', Array)
#1 ...\library\Bvb\Grid.php(2317): Bvb_Grid-&gt;_buildFiltersValues()
#2 ...\library\Bvb\Grid\Deploy\Table.php(1604): Bvb_Grid-&gt;deploy()
#3 ...\application\controllers\AdminController.php(99): Bvb_Grid_Deploy_Table-&gt;deploy()
#4 ...\library\Zend\Controller\Action.php(513): AdminController-&gt;usersAction()
#5 ...\library\Zend\Controller\Dispatcher\Standard.php(289): Zend_Controller_Action-&gt;dispatch('usersAction')
#6 ...\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard-&gt;dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#7 ...\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front-&gt;dispatch()
#8 ...\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap-&gt;run()
#9 ...\index.php(26): Zend_Application-&gt;run()
#10 {main}

Request Parameters:

array (
  'controller' =&gt; 'admin',
  'action' =&gt; 'users',
  'order' =&gt; 'fio_ASC',
  'company' =&gt; 'adfa',
  'module' =&gt; 'default',
)  

During debugging the file bvb/grid/source/zend/select.php in the code  &quot;$extra = isset($full['extra']) ? $full['extra'] : 'boolean';

```
    if ( ! in_array($extra, array('boolean', 'queryExpansion', false)) ) {
        throw new Bvb_Grid_Exception('Unrecognized value in extra key');
    }&quot;
```

the variable $extra for some reason has value &quot;c&quot;

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=373_

**Comment by imonteiro** [comment]
_From Vlad.Ovc...@gmail.com on July 09, 2010 10:20:16_
That helped me:

Bvb/Grid.php

//Old code:
$this->getSource()->addFullTextSearch($filter, $key, $this->_data['fields'][$key]);

// My code:
$this->getSource()->addFullTextSearch($filter, $this->_data['fields'][$key]);

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on July 12, 2010 15:56:18_
Hi,

You are completely right.

Thanks for the report and fix

Best Regards,
Bento Vilas Boas
