### ISSUE TITLE
Filter error.. UTF8 / Latin1

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#538]
_Original author: tho...@valepizza.com (July 01, 2010 20:02:04)_

When i use the ç in text filter, return this error:

Message: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (latin1_general_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation 'like' 
#4 C:\Projetos\open\Aprovesc\financeiro\library\Bvb\Grid\Source\Zend\Select.php(251): Zend_Db_Select-&gt;query(2)
#5 C:\Projetos\open\Aprovesc\financeiro\library\Bvb\Grid.php(2325): Bvb_Grid_Source_Zend_Select-&gt;execute()
#6 C:\Projetos\open\Aprovesc\financeiro\library\Bvb\Grid\Deploy\Table.php(1595): Bvb_Grid-&gt;deploy()

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=364_

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on July 04, 2010 15:34:32_
HI,
This is not related with ZFDatagrid.

It seams that your are using different collations in your tables. 

Also don't forget to set the same encoding in your grid (may be the problem).

$view = new Zend_View();
$view->setEncoding('ISO-8859-1');
$grid->setView($view);

Best Regards,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on July 05, 2010 17:47:14_
yes.. 

i replace the URF-8 project files to ISO-8859-1.. 
and set ISO-8859-1 view encoding.
the same charset as the database... now works!
