### ISSUE TITLE
addClassCellCondition

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#552]
_Original author: gibler...@gmail.com (June 21, 2010 07:09:46)_

<b>What steps will reproduce the problem?</b>
1. applying this function to the grid in the controller:

$grid-&gt;addClassCellCondition('marker_1',&quot;substr('{{marker_1}}',-1)=='{{marked_status}}'&quot;,&quot;green&quot;);
1. Export to PDF, Print, WordX or Excel
2. Exception is thrown

<b>What is the expected output? What do you see instead?</b>

Seeing this error instead of PDF, Print, Excel Output:

Fatal error: Uncaught exception 'Bvb_Grid_Exception' with message 'call to unknown function addClassCellCondition' in /var/www/zend_sites/case_reporter/library/Bvb/Grid.php:783 Stack trace: #0 [internal function]: Bvb_Grid-&gt;__call('addClassCellCon...', Array) #1 /var/www/zend_sites/case_reporter/application/controllers/AdminController.php(134): Bvb_Grid_Deploy_Print-&gt;addClassCellCondition('marker_1', 'substr('{{marke...', 'green') #2 /var/www/zend_sites/case_reporter/library/Zend/Controller/Action.php(513): AdminController-&gt;seegridAction() #3 /var/www/zend_sites/case_reporter/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action-&gt;dispatch('seegridAction') #4 /var/www/zend_sites/case_reporter/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard-&gt;dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #5 /var/www/zend_sites/case_reporter/public/index.php(45): Zend_Controller_Front-&gt;dispatch() #6 {main} thrown in /var/www/zend_sites/case_reporter/library/Bvb/Grid.php  on line 783

<b>Please insert the appropriate values;</b>
<b>Zend Framework version:</b>
ZFDatgrid Version (Bvb_Grid::getVersion()): 0.6.5
                          Operating system: Ubuntu 9.0.4
                               PHP Version: 5.2.10
               Database Server and version:Postgres 8.4
                          Source Adatapter: Array

<b>Please provide any additional information below.</b>

The grid otherwise works OK display-wise, filters.
Even if I use  $grid-&gt;setPdfGridColumns to restrict fields it still fails.

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=350_

**Comment by imonteiro** [comment]
_From gibler...@gmail.com on June 21, 2010 07:46:54_
My ugly hack is to put:

  else if ($name=="addClassCellCondition") {

  }

in Grid.php at about line 784 just before

else {
            throw new Bvb_Grid_Exception("call to unknown function $name");
        }

:-)

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on June 21, 2010 18:09:37_
Hi,

addClassCellCondition method only works with tables.

That is where the method is declared.

Use the 

$grid->isExport() method to apply conditional methods

<code>

if(!$grid->isExport())
{
$grid->addClassCellCondition('marker_1',"substr('{{marker_1}}',-1)=='{{marked_status}}'","green");

}

</code>

Best Regards,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From federico...@gmail.com on July 25, 2011 10:44:32_
I encountered this issue too. The isExport() seems not mentioned in the documentation.
