### ISSUE TITLE
Error on retrieve data from select

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#564]
_Original author: tho...@valepizza.com (June 17, 2010 16:44:20)_

When i use:
$select = $cr-&gt;select()-&gt;from(array('conta_receber'),
                              array('sha1_id_conta_receber' =&gt; 'sha1(id_conta_receber)','*')) 

Return this error:
Message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'conta_receber.sha1_id_conta_receber' in 'field list' 

This occurred in the last revision

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=338_

**Comment by imonteiro** [comment]
_From tho...@valepizza.com on June 17, 2010 16:46:47_
#4 /var/www/lib/Bvb/Grid/Source/Zend/Select.php(252): Zend_Db_Select->query(2)
#5 /var/www/lib/Bvb/Grid.php(2316): Bvb_Grid_Source_Zend_Select->execute()
#6 /var/www/lib/Bvb/Grid/Deploy/Table.php(1609): Bvb_Grid->deploy()

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on June 17, 2010 17:17:16_
Hi Thomas,

Thanks for the report.

Fixed and committed.

Best Regards,
Bento Vilas Boas
