### ISSUE TITLE
Grid error when deleting

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#566]
_Original author: Guus.Te...@gmail.com (June 17, 2010 13:49:43)_

<b>What steps will reproduce the problem?</b>
1.Create Grid
2.Specify only setDelete(true)
3.Try to delete a record

<b>What is the expected output? What do you see instead?</b>
Expected: Records gets deleted.
Got:

An error occurred
Application error
Exception information:

Message: Resource 'comm' not found
Stack trace:
#0 /usr/local/share/ZendFramework/library/Zend/Acl.php(774): Zend_Acl-&gt;get('comm')
#1 /usr/local/share/vhosts/machWeb/application/plugins/AccessCheck.php(25): Zend_Acl-&gt;isAllowed('admin', 'comm', 'mode:delete;[lo...')
#2 /usr/local/share/ZendFramework/library/Zend/Controller/Plugin/Broker.php(309): Application_Plugin_AccessCheck-&gt;preDispatch(Object(Zend_Controller_Request_Http))
#3 /usr/local/share/ZendFramework/library/Zend/Controller/Front.php(941): Zend_Controller_Plugin_Broker-&gt;preDispatch(Object(Zend_Controller_Request_Http))
#4 /usr/local/share/ZendFramework/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front-&gt;dispatch()
#5 /usr/local/share/ZendFramework/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap-&gt;run()
#6 /usr/local/share/vhosts/machWeb/public/index.php(29): Zend_Application-&gt;run()
#7 {main}

Request Parameters:

array (
  'controller' =&gt; 'comm',
  'action' =&gt; 'mode:delete;[loginHist.loginHistID:2]',
  'module' =&gt; 'default',
)  

User : support@maa.nl
Zend version :1.10.5
Bvb_Grid version : $Rev: 1246 $ 

<b>Please insert the appropriate values;</b>
<b>Zend Framework version:</b>
<b>ZFDatgrid Version (Bvb_Grid::getVersion()):</b>
<b>Operating system:</b>
<b>PHP Version:</b>
<b>Database Server and version:</b>
<b>Source Adatapter:</b>

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=336_

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on June 17, 2010 14:05:32_
Hi,

Can you please provide the url created when trying to delete the record.

Are you using Ajax?

Best Regards,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From Guus.Te...@gmail.com on June 18, 2010 06:51:29_
As shown in the error message:
http://mach.mhs.nl/comm/mode:delete;[loginHist.loginHistID:101]

No Ajax.

**Comment by imonteiro** [comment]
_From Guus.Te...@gmail.com on June 22, 2010 07:58:02_
Hello Bento,

I just found out that deleting through the mass updates does work.

**Comment by imonteiro** [comment]
_From Guus.Te...@gmail.com on June 22, 2010 10:28:28_
FYI: the error comes from the Zend_Acl not knowing the called resource 'comm'.
So it looks like you are implementing a delete through a public defined controller/action that is not known to the site.
I guess there is some lacking $grid->getUrl() in front of the uri or something like that.

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on June 22, 2010 13:30:35_
Hi,

Are you using routes?

Best Regards,
Bento Vilas Boas
