### ISSUE TITLE
$grid->setSqlExp error

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#607]
_Original author: tho...@valepizza.com (May 22, 2010 17:50:39)_

show error when use one calculed column

...
select()-&gt;columns(array('calc'=&gt;new Zend_Db_Expr(' TIMEDIFF(XX,YY)')))
...
$grid-&gt;setSqlExp(array('calc' =&gt; array('functions' =&gt; array('AVG')));

 Message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'calc' in
'field list'
Stack trace:
#0 C:\Zend\includes\Zend\Db\Statement.php(320):

Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 C:\Zend\includes\Zend\Db\Adapter\Abstract.php(468):

Zend_Db_Statement-&gt;execute(Array)
#2 C:\Zend\includes\Zend\Db\Adapter\Pdo\Abstract.php(238):

Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Table_Select), Array)
#3 C:\Zend\includes\Zend\Db\Select.php(686):

Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Table_Select))
#4

C:\Projetos\thomas\valepizzaV3\library\Bvb\Grid\Source\Zend\Select.php(568): Zend_Db_Select-&gt;query(2)
#5 C:\Projetos\thomas\valepizzaV3\library\Bvb\Grid.php(1848):

Bvb_Grid_Source_Zend_Select-&gt;getSqlExp(Array, Array)
#6 C:\Projetos\thomas\valepizzaV3\library\Bvb\Grid\Deploy\Table.php(1617):

Bvb_Grid-&gt;_buildSqlExp()
#7 C:\Projetos\thomas\valepizzaV3\library\Bvb\Grid\Deploy\Table.php(1545):

Bvb_Grid_Deploy_Table-&gt;_buildGridRender()

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=295_

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on May 23, 2010 19:17:02_
Hi,

Thanks for the report.

Fixed. Please update tot the latest revision 1193

Best Regards,
Bento Vilas Boas
