### ISSUE TITLE
Decodin

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#708]
_Original author: diegoalb...@gmail.com (February 23, 2010 15:59:13)_

<b>What steps will reproduce the problem?</b>
1. Create a basic grid inside a controller
2. Make a filter, then go to another controller
3. Get back to the grid

<b>What is the expected output? What do you see instead?</b>

Grid but recieved the following:

Message: Decoding failed: Syntax error

Stack trace:
#0 C:\home\lgecb.net\library\Bvb\Grid\DataGrid.php(1106):

Zend_Json::decode('')
#1 C:\home\lgecb.net\library\Bvb\Grid\DataGrid.php(2648):

Bvb_Grid_DataGrid-&gt;buildQueryWhere()
#2 C:\home\lgecb.net\library\Bvb\Grid\DataGrid.php(2689):

Bvb_Grid_DataGrid-&gt;getQueryCount()
#3 C:\home\lgecb.net\library\Bvb\Grid\Deploy\Table.php(1858):

Bvb_Grid_DataGrid-&gt;deploy()
#4 C:\home\lgecb.net\application\controllers\UserController.php(241):

Bvb_Grid_Deploy_Table-&gt;deploy()
#5 C:\usr\share\lib\library\Zend\Controller\Action.php(513):

UserController-&gt;listAction()
#6 C:\usr\share\lib\library\Zend\Controller\Dispatcher\Standard.php(289):

Zend_Controller_Action-&gt;dispatch('listAction')
#7 C:\usr\share\lib\library\Zend\Controller\Front.php(954):

Zend_Controller_Dispatcher_Standard-
&gt;dispatch(Object(Zend_Controller_Request_Http), 
Object(Zend_Controller_Response_Http))
#8 C:\usr\share\lib\library\Zend\Application\Bootstrap\Bootstrap.php(97):

Zend_Controller_Front-&gt;dispatch()
#9 C:\usr\share\lib\library\Zend\Application.php(366):

Zend_Application_Bootstrap_Bootstrap-&gt;run()
#10 C:\home\lgecb.net\public_html\index.php(29): Zend_Application-&gt;run()
#11 {main}

Request Parameters:

array (
  'module' =&gt; 'default',
  'controller' =&gt; 'user',
  'action' =&gt; 'list',
)  

<b>What version of the product are you using? On what operating system?</b>

XP SP3, 0.5

<b>Please provide any additional information below.</b>

We fixed the error adding the following line to the Bvb_Grid_DataGrid at 
line 1106         if(!empty($filters)) $filters = Zend_Json::decode ( 
$filters );

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=187_

**Comment by imonteiro** [comment]
_From pao.fre...@gmail.com on February 23, 2010 19:48:15_
Hi,

Thanks for this report.

This was already fixed on version 0.6

Best Regards,
Bento Vilas Boas
