### ISSUE TITLE
massActions fail on non-default table schema

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#78]
_Original author: tom.rear...@gmail.com (April 18, 2012 15:40:57)_

<b>What steps will reproduce the problem?</b>
1. Enable massActions on a grid
2. Load the table with a _non-default_ table schema
3. deploy grid

<b>What is the expected output? What do you see instead?</b>
Should see a rendered table. Get following trace:

In trace below, default schema is 'meta' but table is defined as 'evidence.items'. 'evidence' is getting lost.
#0 C:\wamp\www\Meta\library\Zend\Db\Statement.php(300): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 C:\wamp\www\Meta\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Statement-&gt;execute(Array)
#2 C:\wamp\www\Meta\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query('DESCRIBE `items...', Array)
#3 C:\wamp\www\Meta\library\Zend\Db\Adapter\Pdo\Mysql.php(169): Zend_Db_Adapter_Pdo_Abstract-&gt;query('DESCRIBE `items...')
#4 C:\wamp\www\Meta\library\Bvb\Grid\Source\Zend\Select.php(245): Zend_Db_Adapter_Pdo_Mysql-&gt;describeTable('items', NULL)
#5 C:\wamp\www\Meta\library\Bvb\Grid\Source\Zend\Select.php(1415): Bvb_Grid_Source_Zend_Select-&gt;getDescribeTable('items')
#6 C:\wamp\www\Meta\library\Bvb\Grid.php(4527): Bvb_Grid_Source_Zend_Select-&gt;getIdentifierColumns('items', 'evidence')
#7 C:\wamp\www\Meta\library\Bvb\Grid\Deploy\Table.php(3423): Bvb_Grid-&gt;_getMassActionsDecorator()
#8 C:\wamp\www\Meta\library\Bvb\Grid\Deploy\Table.php(1994): Bvb_Grid_Deploy_Table-&gt;_buildMassActions()
#9 C:\wamp\www\Meta\library\Bvb\Grid\Deploy\Table.php(1926): Bvb_Grid_Deploy_Table-&gt;_buildGridRender()

<b>Please insert the appropriate values;</b>
                    Zend Framework version: 1.11.11
ZFDatgrid Version (Bvb_Grid::getVersion()): 0.8
                          Operating system: Win7
                               PHP Version: 5.3.3
               Database Server and version: MySql 5.0.7

To fix:
In Bvb_Grid_Source_Zend_Select:  Select.php, change line 1413 from

```
public function getIdentifierColumns($table)
{
    $pk = $this-&gt;getDescribeTable($table);
```

to
    public function getIdentifierColumns($table, $schema = null)
    {
        $pk = $this-&gt;getDescribeTable($table, $schema);

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=854_

**Comment by imonteiro** [comment]
_From licentia...@gmail.com on May 06, 2012 17:07:26_
Hi,

Thanks for the fix.

regards,
